name: Publish Package to npmjs
on: 
  workflow_dispatch:
    inputs:
      revision:
        description: 'Revision'
        required: true
        default: 'prerelease'
        type: choice
        options:
        - prerelease
        - minor
        - major
  # release:
  #   types: [released]
jobs:
  publish-mangrove-js:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Node Install
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com'

    - name: create .npmrc
      run: |
        echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > .npmrc
        echo "registry=https://registry.npmjs.org/" >> .npmrc
        echo "always-auth=true" >> .npmrc
        cp .npmrc /tmp/.npmrc
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    - name: create .yarnrc
      run: |
        echo "npmRegistryServer: https://npm.pkg.github.com" > .yarnrc
        echo "npmAuthToken: ${NODE_AUTH_TOKEN}" >> .yarnrc
        cp .yarnrc /tmp/.yarnrc
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    - name: Setup yarn
      run: npm install -g yarn@2.4.3

    - run: yarn --version
    - run: yarn

    - name: Bump version
      run: |
        echo $INPUT_REVISION
        npm version --no-git-tag-version $INPUT_REVISION
      env:
        INPUT_REVISION: ${{ inputs.revision }}

    - name: Publish
      run: |
        if [ "$INPUT_REVISION" = "prerelease" ]; then
          tag="next"
        else
          tag="latest"
        fi
        yarn npm publish --access public --tag $tag
      env:
        INPUT_REVISION: ${{ inputs.revision }}

    - name: setup git
      run: |
        echo "INPUT_COMMIT_USER_NAME: ${INPUT_COMMIT_USER_NAME}";
        git config --global user.name  "${INPUT_COMMIT_USER_NAME}";
        echo "INPUT_COMMIT_USER_EMAIL: ${INPUT_COMMIT_USER_EMAIL}";
        git config --global user.email ${INPUT_COMMIT_USER_EMAIL}

      env:
        INPUT_COMMIT_USER_NAME:  github-actions-bot[${{ github.actor }}]
        INPUT_COMMIT_USER_EMAIL: github-actions-bot[${{ github.actor }}]@users.noreply.github.com

    - name: git version
      run: |
        git status
        git add package.json yarn.lock
        PACKAGE_VERSION=$(cat package.json \
        | grep version \
        | head -1 \
        | awk -F: '{ print $2 }' \
        | sed 's/[",]//g')
        git commit -m $PACKAGE_VERSION
        git push
    # - name: Play with tag
    #   run: yarn version $TAG
    #   env:
    #     TAG: "1.2.4-10-test"

    # - name: mangrove.js - Publish
    #   run: cat /tmp/.npmrc &&  npm publish --tag next
